spring:
  application:
    name: emp-service
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3307}/${DATABASE:training}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root}
  jpa:
    show_sql: true
server:
  port: 8081


